# Generated by Django 5.1.3 on 2025-01-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpt',
            fields=[
                ('dname', models.CharField(max_length=100)),
                ('dpt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('sal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=100)),
                ('hiredate', models.DateField()),
                ('comm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dpt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dpt')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
